site_name: Vibration Spectroscopy Ontology Documentation
theme:
  name: material
  features:
    - content.tabs.link
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

site_url: https://NFDI4Chem.github.io/VibrationSpectroscopyOntology/
repo_url: https://github.com/NFDI4Chem/VibrationSpectroscopyOntology/

nav:
  - About VISBO:
      - Introduction: index.md
      - Domain Definition: domain_definition.md
      - Competency Questions: competency_questions.md
      - Development Approach: development_approach.md
      - Design Patterns & Decisions: design_patterns.md
  - How-to guides:
      - Contributing To VIBSO:
          - Getting Started: contributing.md
          - New Term Requests: ntr_workflow.md
      - Standard ODK workflows:
          - Default ODK Workflows: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Components management: odk-workflows/components.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
  - ODK Specific Documentation:
      - Repository Overview: odk-workflows/RepositoryFileStructure.md
      - Continuous Integration: odk-workflows/ContinuousIntegration.md
  - Cite: cite.md
